#!/usr/bin/bash

# Exit on errors, undefined variables, and otherwise masked pipeline errors.
set -euo pipefail
# Internal Field Separator: Split new-lines and tabs, not spaces.
IFS=$'\n\t'

readonly CONF_FILE="zict.bash"
readonly CONF_CUSTOM_PATH="${XDG_CONFIG_HOME:-$HOME/.config}/zict/$CONF_FILE"
readonly CONF_DEFAULT_PATH="/etc/zict/$CONF_FILE"

# Show help message.
cmd_help() {

    sed 's/^    //' <<EOF
    Usage: $(basename "$0") ( en | ru ) <phrase>
        Options:
            -h, --help, help
                Show this help message.

            -d, --download, download ( en | ru )
                Download the specified dictionary.

            -s, --search, search ( en | ru )
                Search the specified dictionary.

            --copy-config
                Create a copy of the default configuration file in your local
                configuration directory.
                '$CONF_DEFAULT_PATH' -> '$CONF_CUSTOM_PATH'

        Examples:

        # View English definition for "a lot".
        zict en a lot

        # View Russian definition for "a lot".
        zict ru a lot

        # Search English phrases like "a lot".
        zict search en a lot

        # Search English phrases like "a lot".
        zict search ru a lot

        # Continue downloading English dictionary after canceling download.
        zict download en

        # Download Russian dictionary.
        zict download ru
EOF

}

cmd_search() {
    local -r wiktionary_file="$1"
    local -r phrase="${*:2}"
    zimsearch "$wiktionary_file" "$phrase" |
        awk '/^score/ { for (i=4; i < NF; ++i) printf $i FS; printf $NF"\n" }'
}

cmd_download() {
    local -r download_dir="$1"
    local -r download_url="$2"
    wget --directory-prefix "$download_dir" "$download_url" --continue
}

# Direct output to stderr.
err() {
    echo "$*" >&2
}

cmd_copy_config() {
    mkdir --parents --verbose "$(dirname "$CONF_CUSTOM_PATH")"
    cp --no-clobber --verbose "$CONF_DEFAULT_PATH" "$CONF_CUSTOM_PATH"
}

get_config_file() {
    if [[ -f "$CONF_CUSTOM_PATH" ]]; then
        echo "$CONF_CUSTOM_PATH"
    elif [[ -f "$CONF_DEFAULT_PATH" ]]; then
        echo "$CONF_DEFAULT_PATH"
    else
        err "Error: Could not load: '$CONF_DEFAULT_PATH' nor '$CONF_CUSTOM_PATH'"
        exit 1
    fi
}

view() {
    local -r wiktionary="$1"; shift
    # Replace all spaces with underscores.
    local -r word="${*// /_}"
    # Store current keyboard layout.
    local -r layout="$(setxkbmap -query | awk '/layout:/ { print $2 }')"
    # Set keyboard to English so that keybindings work in w3m.
    setxkbmap -layout us
    # Display definition.
    zimdump show --url="$word" "$wiktionary" | w3m -T text/html
    # Restore previous keyboard layout.
    setxkbmap -layout "$layout"
}

main() {
    # shellcheck disable=1090
    source "$(get_config_file)"

    case "$1" in
    --ru | ru | --en | en)
        view "${CONF_WIKTIONARY_PATH["${1#--}"]}" "${*:2}"
        ;;
    -d | --download | download)
        shift
        cmd_download "$CONF_DOWNLOAD_DIR" "${CONF_WIKTIONARY_DOWNLOAD_URL[$1]}"
        exit 0
        ;;
    -s | --search | search)
        shift
        cmd_search "${CONF_WIKTIONARY_PATH["$1"]}" "${@:2}"
        exit 0
        ;;
    -h | --help | help)
        cmd_help
        exit 0
        ;;
    --copy-config)
        cmd_copy_config
        exit 0
        ;;
    *)
        cmd_help
        exit 1
        ;;
    esac
    exit 0
}

main "$@"
